### ISSUE TITLE
Modustoolbox BLE examples

### ISSUE THREAD

**Issue by henri98** [cypresssemiconductorco/Code-Examples-for-the-ModusToolbox-PSoC-6-SDK#1]
Where can I find more ModusToolbox BLE examples? Or can they be added? Maybe something in combination with FreeRTOS or something with bonding and custom services.

**Comment by JimTrudeau** [comment]
Henri98 - all the times I have been here, I did not notice the issue, my apologies.

For PSoC 6 and PSoC Creator there is a pretty good collection, but I don't think they use FreeRTOS. They are here: https://github.com/cypresssemiconductorco/PSoC-6-MCU-BLE-Connectivity-Designs. Over time some of these will migrate to the ModusToolbox environment.
