### ISSUE TITLE
How to change PLL clock frequency with C

### ISSUE THREAD

**Issue by find1dream** [cypresssemiconductorco/Code-Examples-for-the-ModusToolbox-PSoC-6-SDK#3]
**Question/Issue**:
I want to run the CPU at 150MHz, how can I achieve it? Can you provide me any document or code?

**Context**
os: macOS: 1015.4
chip: CY8CPROTO-062-4343W PSoC 6 Wi-Fi BT PROTOTYPING KIT
environment: terminal

**Comment by rmbk19** [comment]
Hi @find1dream, 

There are 2 ways to configure the PLL. 
1. You can use the Device Configurator > System tab and configure the PLL frequency. For information regarding the Device Configurator, you can refer to the [ModusToolbox Device Configurator Guide](https://www.cypress.com/file/504376/download)
2. You can manually configure the PLL using the PDL SysClk driver about which you can learn about [here](https://cypresssemiconductorco.github.io/psoc6pdl/pdl_api_reference_manual/html/group__group__sysclk__pll.html )

Please let me know if this helps.

Thanks and Regards, 
Rakshith M B

**Comment by JimTrudeau** [comment]
I'm going to assume resolved. Thanks for raising the question.
